### ISSUE TITLE
Can't compile aframe-physics-system with three-to-cannon 3.0.2

### ISSUE THREAD

**Issue by MignonBelongie** [donmccurdy/three-to-cannon#28]
I'm having trouble figuring out how to use the latest three-to-cannon in aframe-physics-system. There's some discussion in https://github.com/n5ro/aframe-physics-system/pull/172, but that might be more than you want to read, so I'll summarize here.

When I ran  
```
browserify index.js -o bundle.js
```
after updating three-to-cannon to 3.0.2, I got the following error:
```
Error: Cannot find module 'three' from 'D:\src\aframe-physics-system\node_modules\three-to-cannon\dist'
```
So I added three as a dependency. Then browserify succeeded, and everything worked when I loaded bundle.js in the browser, e.g. in `examples/cannon.html`. What I didn't notice at first was that all of three.js was included in bundle.js, which was therefore huge. If I exclude three, i.e.
```
browserify -x three index.js  -o bundle.js
```
then I get a small bundle, but I get an error in the browser:
```
Uncaught Error: Cannot find module 'three'
	at o (bundle.js:1)
	at bundle.js:1
	at Object.6.cannon-es (bundle.js:14226)
	at o (bundle.js:1)
	at bundle.js:1
	at Object.10.../../../lib/CANNON-shape2mesh (bundle.js:14980)
	at o (bundle.js:1)
	at bundle.js:1
	at Object.1../src/components/ammo-constraint (bundle.js:6)
	at o (bundle.js:1)
```
If I manually replace `t=require("three")` with `t=THREE` in bundle.js, then everything is great. To try to achieve that result, I tried using exposify or browserify-shim, which seem designed for this. Unfortunately, they seem to have no effect on require statements in required packages, specifically the `require("three")` in three-to-cannon.js.

I also tried making three a peer dependency instead of a regular dependency, but still no luck. For example, I tried the following in package.json:
```
"scripts": {
  ...
  "dist2": "browserify index.js -o bundle.js",
  ...
},
"browserify": {
  "transform": [
    "browserify-shim"
  ]
},
"browserify-shim": {
  "three": "global:THREE"
},
"dependencies": {
  "ammo-debug-drawer": "^0.1.0",
  "cannon-es": "^0.9.1",
  "three-to-ammo": "^0.1.0",
  "three-to-cannon": "^3.0.2",
  "webworkify": "^1.4.0"
},
"peerDependencies": {
  "aframe": ">=0.5.0",
  "three": "^0.115.0"
},
```
Can you help me figure out how to compile aframe-physics-system with three-to-cannon 3.0.2?

**Comment by donmccurdy** [comment]
> ... I tried using exposify or browserify-shim, which seem designed for this. Unfortunately, they seem to have no effect on require statements in required packages, specifically the require("three") in three-to-cannon.js.

This looks like the right approach — maybe you need a `depends` rule for three-to-cannon, when using browserify-shim with a `global:THREE` rule? Is three-to-cannon being embedded in the bundle, do you know?

If that's not working, is there a git branch I can test out using browserify-shim?

**Comment by Galadirith** [comment]
@MignonBelongie really great find on `browserify-shim`, and thanks so much @donmccurdy for looking at this. Because it has no effect on `three-to-canon` it looks like transforms like `browserify-shim` are not global by default, but it looks like you can change that behaviour with [`--global-transform`](https://github.com/browserify/browserify#usage), so a candidate solution might be

```
browserify -x three index.js  -g browserify-shim -o bundle.js
```

**Comment by MignonBelongie** [comment]
@Galadirith  Making it a global transform turned out to be the trick. Thanks! Interestingly, I also no longer needed  `-x three`.
See https://github.com/n5ro/aframe-physics-system/pull/172/commits/85aa3c3f12125ac84f34e3ac7ca96397cc0e35d4
